version: '2'

services:
  imapsync:
    hostname: imapsync
    build: ./imapsync
    links:
      - "mail"
  mail:
    image: tvial/docker-mailserver:v2
    hostname: mail
    domainname: imapsync.local
    ports:
      #- "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN
  nginx:
    image: nginx:1.11-alpine
    hostname: web
    ports:
      - "8080:80"
    volumes:
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - data
    links:
      - "php"
      - "mail"
  php:
    hostname: php
    image: php:5.6-fpm-alpine
    volumes_from:
      - data
  data:
    build:
      context: .
      dockerfile: rainloop/Dockerfile
    volumes:
      - /rainloop

volumes:
  maildata:
    driver: local
