version: '2'

services:
  mailbackup:
    hostname: mailbackup
    domainname: mailbackup.local
    build:
      context: mailsrv
    ports:
      - "8143:143"
      #- "25:25"
      #- "587:587"
      #- "993:993"
    volumes:
      - maildata:/var/mail
      - ./config:/tmp/docker-mailserver/
    env_file:
      - imapsync.env
    environment:
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN
  nginx:
    hostname: web
    build:
      context: nginx
    ports:
      - "8080:80"
    volumes_from:
      - webdata
    links:
      - "php"
      - "mailbackup"
  php:
    hostname: php
    image: php:5.6-fpm-alpine
    volumes_from:
      - webdata
    env_file:
      - imapsync.env
    environment:
      - ENCRYPTION_KEY
  webdata:
    build:
      context: roundcube
    volumes:
      - /web
      - /rc

volumes:
  maildata:
    driver: local
